# Generated by Django 5.0.7 on 2024-09-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest-user', 'Guest User'), ('loggedin-user', 'Logged In User'), ('vendor-admin', 'Vendor Admin'), ('super-admin', 'Super Admin')], default='guest-user', max_length=20),
        ),
    ]
