# Generated by Django 5.0.7 on 2024-09-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest-user', 'GuestUser'), ('loggedin-user', 'LoggedInUser'), ('vendor-admin', 'VendorAdmin'), ('super-admin', 'SuperAdmin')], default='guest-user', max_length=20),
        ),
    ]
